[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sunagent-app"
version = "0.0.26b12"
license = {file = "LICENSE-CODE"}
description = "sunagent app"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "autogen-core",
  "openpyxl",
  "autogen-ext",
  "sunagent-ext>=0.0.6b10",
  "autogen-agentchat",
  "prometheus_client",
  "autogen",
  "flask[async]",
  "flask_cors",
  "quart",
  "tweepy",
  "aiohttp",
  "async_lru",
  "apscheduler",
  "beem",
  "oauthlib",
  "pytz",
  "google-genai",
]

[dependency-groups]
dev = [
  "types-pytz",
  "types-requests",
]

[tool.hatch.version]
path = "src/sunagent_app/version.py"

[project.scripts]
sunagent_app = "sunagent_app.app:main"

[tool.ruff]
extend = "../../pyproject.toml"
include = ["src/**", "tests/*.py"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["tests"]

[tool.mypy.overrides]
"tweepy" = { ignore_errors = true }

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
test = "pytest -n auto"
