[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sunagent-ext"
version = "0.0.6b10"
license = {file = "LICENSE-CODE"}
description = "AutoGen extensions library"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "autogen-core==0.4.9",
    "aiohttp",
    "onepassword-sdk>=0.3.0",
    "pytz",
    "redis",
    "requests",
]

[project.optional-dependencies]
dev = [
  "types-requests",
]
langchain = ["langchain_core~= 0.3.3"]
azure = [
    "azure-ai-inference>=1.0.0b7",
    "azure-core",
    "azure-identity",
]

[tool.hatch.build.targets.wheel]
packages = ["src/sunagent_ext"]


[tool.ruff]
extend = "../../pyproject.toml"
include = ["src/**", "tests/*.py"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["tests"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
markers = [
    "grpc",
]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.mypy]
ignore_missing_imports = true
